# METIS Intro to Data Science Project

## By: Ben McGauhey

### Seattle, WA Fall-2017

# Predictive Model
We will be building a model that will attempt to predict the nature of a call, using our best features from the data. The initial goal of this project was to explore what effect the weather has on crime, using 911 call data as our proxy. In exploring our data, we have learned that there are correlations in our data, but none that are strong enough even in combinatio

In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.externals.six import StringIO
import matplotlib.pyplot as plt

In [2]:
df = pd.read_pickle('Data/modelData.pkl')

In [3]:
df

,longitude,latitude,formatted_time,homicide,robbery,assault,burglary,theft,car_theft,reckless_burning,...,mist,overcast_clouds,proximity_thunderstorm,scattered_clouds,sky_is_clear,smoke,snow,thunderstorm,hour,rain
0,-122.325060,47.597930,2017-02-15 21:15:45,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,21,1
1,-122.345860,47.612990,2016-02-11 13:21:02,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,13,0
2,-122.319282,47.549830,2014-12-07 14:00:00,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,14,0
3,-122.338860,47.661385,2017-02-28 17:10:27,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,17,0
4,-122.311530,47.595870,2017-08-13 01:56:59,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
5,-122.322451,47.601702,2015-03-14 16:29:00,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,16,0
6,-122.265071,47.528513,2012-10-05 11:13:00,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,11,0
7,-122.355515,47.713253,2017-07-11 23:03:28,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,23,0
8,-122.360959,47.541219,2015-10-24 14:30:00,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,14,0
9,-122.351110,47.534130,2017-01-27 17:50:16,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,17,0
10,-122.255900,47.508953,2016-06-03 04:59:26,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,4,0
11,-122.270510,47.537960,2016-02-02 04:06:56,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,4,0
12,-122.334010,47.610646,2015-08-10 12:55:00,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,12,0
13,-122.270911,47.555988,2014-12-09 10:31:00,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,10,0
14,-122.301444,47.610801,2015-07-02 20:46:00,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,20,0
15,-122.372590,47.529190,2017-09-20 04:56:09,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,4,1
16,-122.331390,47.601074,2016-03-30 10:01:04,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,10,0
17,-122.321770,47.589085,2016-01-27 03:12:53,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,3,0
18,-122.331730,47.603127,2017-01-29 06:59:00,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,6,0
19,-122.315680,47.599200,2014-12-09 19:22:00,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,19,0
20,-122.299463,47.608002,2013-02-01 12:14:00,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,12,0
21,-122.301520,47.582760,2017-05-04 00:07:13,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22,-122.411964,47.578740,2017-05-24 06:50:32,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,0
23,-122.333040,47.604554,2014-12-04 13:42:00,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,13,0
24,-122.327021,47.597516,2015-06-28 02:51:00,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,2,0
25,-122.286030,47.562830,2017-07-10 00:32:05,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,-122.326355,47.600451,2014-12-02 13:34:00,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,13,0
27,-122.370490,47.663660,2017-04-28 11:59:47,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,11,0
28,-122.321030,47.599190,2017-09-13 21:47:30,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,21,0
29,-122.306280,47.690300,2016-02-22 07:21:44,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878450,-122.306680,47.626846,2017-10-11 08:37:35,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,8,0
878451,-122.311910,47.562622,2017-09-14 10:04:14,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,10,0
878452,-122.282100,47.546005,2017-04-26 16:58:27,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,16,1
878453,-122.295520,47.550854,2017-09-14 08:08:31,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,8,0
878454,-122.376175,47.643856,2017-04-24 13:29:03,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,13,1
878455,-122.295520,47.550854,2017-10-12 08:18:49,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878456,-122.298134,47.585480,2017-10-03 13:16:58,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,13,0
878457,-122.311910,47.562622,2017-10-03 14:05:20,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,14,0
878458,-122.376560,47.540130,2017-05-30 08:55:31,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,8,0
878459,-122.400986,47.640846,2017-05-18 10:36:05,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,10,0
878460,-122.303060,47.643154,2017-09-13 09:25:27,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,9,0
878461,-122.286070,47.708320,2017-10-10 08:43:46,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878462,-122.400986,47.640846,2017-06-14 10:51:01,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,10,0
878463,-122.311910,47.562622,2017-10-12 08:58:37,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878464,-122.400986,47.640846,2017-06-09 10:31:59,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,10,0
878465,-122.314545,47.601690,2017-09-13 08:04:58,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,8,0
878466,-122.311910,47.562622,2017-09-28 09:03:43,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,9,1
878467,-122.400980,47.642178,2017-04-20 10:53:05,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,1
878468,-122.339440,47.562325,2017-10-13 08:33:41,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878469,-122.400986,47.640846,2017-05-31 10:26:37,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
878470,-122.295520,47.550854,2017-09-28 08:01:14,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878471,-122.334210,47.557410,2017-10-13 08:55:45,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878472,-122.400986,47.640846,2017-04-28 10:25:13,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
878473,-122.307900,47.632310,2017-05-10 07:08:19,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,7,0
878474,-122.376560,47.540130,2017-06-08 08:42:51,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,1
878475,-122.400986,47.640846,2017-04-24 10:03:35,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,1
878476,-122.307900,47.632310,2017-05-10 08:06:30,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,8,0
878477,-122.322754,47.614056,2016-11-10 23:45:04,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,23,0
878478,-122.341100,47.611347,2016-04-29 16:00:12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,16,0
878479,-122.347420,47.618275,2017-09-22 01:36:24,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0